### ISSUE TITLE
Doesn't highlight when using ', or when using as an operator

### ISSUE THREAD

**Issue by andrewferrier** [winston0410/mark-radar.nvim#3]
Hi! Nice plugin idea. Tried it out and it seems to work OK so far. However, this doesn't highlight when using the `'` key (as opposed to backtick). Also, probably more crucially, it doesn't work for operator-pending mode (e.g. `c<backtick>a`) (I'm not using the actual backtick char as it messes up GitHub's formatting). This would be great improvements!

Great start...

**Comment by winston0410** [comment]
Hi thank you for this issue. I think it is easy to handle the first one, as I have just forgotten to include the mapping there LOL.

But for the second one, I have actually tried it myself but it won't work. I have tried to map `require('mark-radar').scan()` to `x` mode (which is operator-pending mode), but nothing happens. I would love to know the solution for that as well.

I will keep look for the solution in the meantime.

**Comment by andrewferrier** [comment]
Cool. Sorry, I shouldn't have opened two issues in one! Let me know if you want me to split them. Thanks.

**Comment by winston0410** [comment]
It is alright, just keep this as is. 

I have actually tested today, and it seems like using extmark for highlight in operator-pending mode is possible. I guess the loop was the reason why it doesn't work.

**Comment by andrewferrier** [comment]
Nice! Great progress. In the meantime I've started using your `range-highlight` plugin too. Seems like you're doing great work updating a bunch of plugins for the NeoVim era :)

**Comment by winston0410** [comment]
Hi, the mapping issue for `'` has been addressed in this [commit](https://github.com/winston0410/mark-radar.nvim/commit/f96a2e06996900a2d700675017f8ae91bca8ee6a), do report if something doesn't work well.

Thanks! I found writing pluginfor neovim a fun thing to do, and I want to see how far I can push and make myself more productive with them.

**Comment by winston0410** [comment]
And I have found out the why I cannot make this plugin works in operator-pending mode. I have mistakenly treated `x` for operator-pending mode, yet it should be `o`. You can try the latest commit and it should work now.

**Comment by andrewferrier** [comment]
This is fantastic! It does seem to work now. Seems a bit slow but I'll open that as another issue (I now can't recreate the slowness, will let you know if I do).
