### ISSUE TITLE
mark-radar shows marks at original location even when using single quote

### ISSUE THREAD

**Issue by andrewferrier** [winston0410/mark-radar.nvim#4]
When using single quote, rather than backtick, to navigate to a mark, vim always moves to the beginning of the line, even if the mark was in the middle of the line.

In my opinion, it would be more accurate/helpful to show the mark at the beginning of the line when pressing the single quote key (in normal or operator-pending mode), and show it in its original place when pressing backtick. What do you think?

**Comment by nullromo** [comment]
Furthermore, the default behavior is to jump to the first non-whitespace character of the line (similar to <kbd>^</kbd> in normal mode). However, this plugin causes the cursor to jump to the start of the line (column 0, similar to <kbd>0</kbd> in normal mode).

**Comment by nullromo** [comment]
Closed by #10
